openapi: 3.0.3
info:
  title: Burger Example
  version: 1.0.0
  description: Sample description.
paths:
  /flavors:
    get:
      summary: List All Burgers
      description: Burgers
      parameters:
        - in: query
          name: Calories<
          schema:
            type: string
            description: Calories less than the given amount.
      responses:
        200:
          description: OK
