name: Validate

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'cloud-annotations/docusaurus-plugin-openapi' && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Release
        run: yarn release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
