name: Release

on: [push, pull_request] # TODO: IMPORTANT! ONLY DO THIS ON PUSH

env:
  FORCE_COLOR: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
      - name: Publish
        run: yarn elease:publish --dry-run
