name: Release PR Title Check

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "$PR_TITLE"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
