name: Validate

on: [push, pull_request]

env:
  FORCE_COLOR: true

jobs:
  prepare-yarn-cache:
    name: Prepare Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile

  lint:
    name: Lint
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install
      - name: Check format
        run: yarn format
      - name: Lint
        run: yarn lint --max-warnings 0

  test:
    name: Test
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test

  cypress:
    name: Cypress
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Cypress
        run: yarn test:cypress

  release:
    name: Release
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'cloud-annotations/docusaurus-plugin-openapi' && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v2
        with:
          node-version: "*"
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: yarn install
      - name: Release
        run: yarn release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
